{% set name = "django-localflavor" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11859e522dba74aa6dde5a659242b1fbc5efb4dea08e9b77315402bdeca5194e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2
    - python-stdnum >=1.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - localflavor

about:
  home: https://pypi.org/project/django-localflavor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-localflavor is a collection of assorted pieces of code that are useful for particular countries or cultures. These are called the "local flavor" add-ons

  description: |
    Most of the localflavor add-ons are localized form components deriving from the forms framework – for example, a USStateField that knows how to validate U.S. state abbreviations, and a FISocialSecurityNumber that knows how to validate Finnish social security numbers.

  doc_url: https://django-localflavor.readthedocs.io/
  dev_url: https://github.com/django/django-localflavor/

extra:
  recipe-maintainers:
    - kcemenike
